import os, sys, subprocess

if not (os.path.isdir("backend") and os.path.isdir("frontend")):
    print("ERROR: Run from project root!")
    sys.exit(1)

R = []
R.append("# CyStar \u2014 Selective Disclosure & Verification Module")
R.append("")
R.append("![Python](https://img.shields.io/badge/Python-3.11-blue?logo=python) ![Next.js](https://img.shields.io/badge/Next.js-16-black?logo=next.js) ![FastAPI](https://img.shields.io/badge/FastAPI-0.115-009688?logo=fastapi) ![MongoDB](https://img.shields.io/badge/MongoDB-Atlas-47A248?logo=mongodb) ![Ed25519](https://img.shields.io/badge/Crypto-Ed25519-orange) ![License](https://img.shields.io/badge/License-MIT-green)")
R.append("")
R.append("**IETF SD-JWT based selective disclosure and credential verification system.**")
R.append("")
R.append("> Built for CyStar Summer Internship Assessment \u2014 IIT Madras")
R.append("")
R.append("---")
R.append("")
R.append("## Live Demo")
R.append("")
R.append("| Component | URL |")
R.append("|-----------|-----|")
R.append("| Frontend  | [cystar-selective-disclosure.vercel.app](https://cystar-selective-disclosure.vercel.app) |")
R.append("| Backend   | [cystar-selective-disclosure.onrender.com](https://cystar-selective-disclosure.onrender.com) |")
R.append("| API Docs  | [Swagger UI](https://cystar-selective-disclosure.onrender.com/docs) |")
R.append("")
R.append("> Free-tier Render instances spin down after inactivity. First request may take ~30s.")
R.append("")
R.append("---")
R.append("")
R.append("## Architecture")
R.append("")
R.append("```mermaid")
R.append("sequenceDiagram")
R.append("    participant H as Holder (User)")
R.append("    participant B as Backend (FastAPI)")
R.append("    participant DB as MongoDB Atlas")
R.append("    participant V as Verifier (Public)")
R.append("")
R.append("    Note over H,V: 1. Credential Issuance")
R.append("    H->>B: POST /api/credentials/issue {claims}")
R.append("    B->>B: Generate Ed25519 keypair")
R.append("    B->>B: Create salted disclosure per claim")
R.append("    B->>B: SHA-256 hash each disclosure")
R.append("    B->>B: Build JWT with _sd digest array")
R.append("    B->>B: Sign with Ed25519 (EdDSA)")
R.append("    B->>DB: Store credential + keys + disclosures")
R.append("    B-->>H: Return credential metadata")
R.append("")
R.append("    Note over H,V: 2. Selective Sharing")
R.append("    H->>B: POST /api/credentials/share {credential_id, selected_fields}")
R.append("    B->>DB: Fetch credential")
R.append("    B->>B: Build presentation: JWT ~ selected disclosures only")
R.append("    B->>B: Generate UUID share token + TTL expiry")
R.append("    B->>DB: Store presentation")
R.append("    B-->>H: Return share_url + QR code data")
R.append("")
R.append("    Note over H,V: 3. Public Verification")
R.append("    V->>B: GET /api/verify/{share_token}")
R.append("    B->>DB: Fetch presentation by token")
R.append("    B->>B: Verify Ed25519 signature on JWT")
R.append("    B->>B: Hash each disclosure, match against _sd digests")
R.append("    B->>B: Decode only matched disclosures")
R.append("    B-->>V: Return {verified, disclosed_fields, hidden_count}")
R.append("```")
R.append("")
R.append("---")
R.append("")
R.append("## Tech Stack")
R.append("")
R.append("| Layer | Technology |")
R.append("|-------|-----------|")
R.append("| Frontend | Next.js 16, TypeScript, Tailwind CSS, shadcn/ui, Sonner, qrcode.react |")
R.append("| Backend | FastAPI, Pydantic v2, Motor (async MongoDB), SlowAPI |")
R.append("| Database | MongoDB Atlas (M0 free tier) |")
R.append("| Cryptography | Ed25519 (PyNaCl), SHA-256, IETF SD-JWT (custom implementation) |")
R.append("| Authentication | JWT (python-jose), bcrypt (passlib) |")
R.append("| Infrastructure | Docker Compose, GitHub Actions CI |")
R.append("| Deployment | Vercel (frontend), Render (backend) |")
R.append("")
R.append("---")
R.append("")
R.append("## SD-JWT: How It Works")
R.append("")
R.append("### 1. Issuance")
R.append("")
R.append("Each claim in a credential is individually processed:")
R.append("")
R.append("```")
R.append('claim: "name" = "Vishnu Aravind"')
R.append("  -> generate random salt")
R.append('  -> disclosure = base64url(json([salt, "name", "Vishnu Aravind"]))')
R.append("  -> hash = SHA-256(disclosure)")
R.append("  -> store hash in JWT payload under _sd array")
R.append("  -> sign entire JWT with Ed25519 private key")
R.append("```")
R.append("")
R.append("The JWT contains only hashes, not actual values. Actual values live in separate disclosure strings.")
R.append("")
R.append("### 2. Selective Sharing")
R.append("")
R.append("The holder chooses which fields to reveal:")
R.append("")
R.append("```")
R.append("SD-JWT: header.payload.signature")
R.append("Presentation: SD-JWT ~ disclosure_name ~ disclosure_degree ~")
R.append("                       (only selected disclosures appended)")
R.append("```")
R.append("")
R.append("Hidden fields have no disclosure attached \u2014 the verifier sees the hash in `_sd` but cannot reverse it.")
R.append("")
R.append("### 3. Verification")
R.append("")
R.append("The verifier receives the presentation and:")
R.append("")
R.append("1. Splits into JWT + disclosures")
R.append("2. Verifies Ed25519 signature on the JWT (tamper detection)")
R.append("3. Hashes each disclosure and checks against `_sd` digests (integrity)")
R.append("4. Decodes matched disclosures to extract claim values")
R.append("5. Reports: disclosed fields, hidden count, issuer, issue date")
R.append("")
R.append("If the signature fails or a disclosure hash doesn't match `_sd`, verification fails.")
R.append("")
R.append("---")
R.append("")
R.append("## Features")
R.append("")
R.append("- **Register / Login** \u2014 JWT-based authentication with bcrypt password hashing")
R.append("- **Issue Credentials** \u2014 Create verifiable credentials with arbitrary custom claims")
R.append("- **Selective Disclosure** \u2014 Field-level checkboxes to choose exactly what to reveal")
R.append("- **QR Code + Link** \u2014 Share credentials via scannable QR or copyable URL")
R.append("- **Public Verification** \u2014 Anyone with the link can verify without logging in")
R.append("- **Ed25519 Signatures** \u2014 Tamper-evident digital signatures on every credential")
R.append("- **Rate Limiting** \u2014 Verification endpoint capped at 10 requests/minute per IP")
R.append("- **Auto-Expiry** \u2014 Share links expire via MongoDB TTL indexes")
R.append("- **Dark UI** \u2014 Responsive, mobile-friendly interface built with Tailwind + shadcn/ui")
R.append("")
R.append("---")
R.append("")
R.append("## Project Structure")
R.append("")
R.append("```")
R.append("cystar-selective-disclosure/")
R.append("├── backend/")
R.append("│   ├── app/")
R.append("│   │   ├── main.py                  # FastAPI app, CORS, routers")
R.append("│   │   ├── core/")
R.append("│   │   │   ├── config.py            # Pydantic settings")
R.append("│   │   │   ├── database.py          # Motor MongoDB client")
R.append("│   │   │   ├── security.py          # JWT + bcrypt")
R.append("│   │   │   └── exceptions.py        # Custom error handling")
R.append("│   │   ├── auth/")
R.append("│   │   │   ├── router.py            # /register, /login")
R.append("│   │   │   ├── service.py           # Auth business logic")
R.append("│   │   │   ├── repository.py        # User CRUD")
R.append("│   │   │   └── schemas.py           # Request/response models")
R.append("│   │   ├── credentials/")
R.append("│   │   │   ├── router.py            # /issue, /share, /list")
R.append("│   │   │   ├── service.py           # Credential business logic")
R.append("│   │   │   ├── repository.py        # Credential + presentation CRUD")
R.append("│   │   │   ├── schemas.py           # Request/response models")
R.append("│   │   │   └── crypto/")
R.append("│   │   │       ├── sd_jwt.py        # SD-JWT create/verify")
R.append("│   │   │       ├── ed25519.py       # Ed25519 sign/verify")
R.append("│   │   │       └── utils.py         # Base64url, SHA-256, disclosures")
R.append("│   │   ├── verification/")
R.append("│   │   │   ├── router.py            # GET /verify/{token}")
R.append("│   │   │   ├── service.py           # Verification logic")
R.append("│   │   │   └── schemas.py           # Response model")
R.append("│   │   └── middleware/")
R.append("│   │       └── rate_limiter.py      # SlowAPI config")
R.append("│   ├── tests/")
R.append("│   │   └── test_sd_jwt.py           # 12 unit tests")
R.append("│   ├── requirements.txt")
R.append("│   ├── Dockerfile")
R.append("│   └── .env.example")
R.append("├── frontend/")
R.append("│   ├── src/")
R.append("│   │   ├── app/")
R.append("│   │   │   ├── page.tsx             # Landing page")
R.append("│   │   │   ├── layout.tsx           # Root layout + AuthProvider")
R.append("│   │   │   ├── (auth)/")
R.append("│   │   │   │   ├── login/page.tsx")
R.append("│   │   │   │   └── register/page.tsx")
R.append("│   │   │   ├── (protected)/")
R.append("│   │   │   │   ├── layout.tsx       # Navbar + auth guard")
R.append("│   │   │   │   ├── dashboard/page.tsx")
R.append("│   │   │   │   ├── issue/page.tsx")
R.append("│   │   │   │   └── share/[id]/page.tsx")
R.append("│   │   │   └── verify/[token]/page.tsx  # Public verification")
R.append("│   │   ├── lib/")
R.append("│   │   │   ├── api-client.ts        # Axios + interceptors")
R.append("│   │   │   └── auth-context.tsx     # Auth state management")
R.append("│   │   └── types/index.ts           # TypeScript interfaces")
R.append("│   ├── package.json")
R.append("│   ├── Dockerfile")
R.append("│   └── vercel.json")
R.append("├── docker-compose.yml")
R.append("└── .github/workflows/ci.yml")
R.append("```")
R.append("")
R.append("---")
R.append("")
R.append("## API Documentation")
R.append("")
R.append("| Method | Endpoint | Auth | Description |")
R.append("|--------|----------|------|-------------|")
R.append("| `POST` | `/api/auth/register` | No | Register new user |")
R.append("| `POST` | `/api/auth/login` | No | Login, get JWT token |")
R.append("| `POST` | `/api/credentials/issue` | Yes | Issue a new credential |")
R.append("| `GET`  | `/api/credentials/` | Yes | List user credentials |")
R.append("| `POST` | `/api/credentials/share` | Yes | Create selective disclosure share link |")
R.append("| `GET`  | `/api/verify/{share_token}` | No | Verify a shared credential (rate-limited) |")
R.append("| `GET`  | `/health` | No | Health check |")
R.append("")
R.append("Full interactive docs: [Swagger UI](https://cystar-selective-disclosure.onrender.com/docs)")
R.append("")
R.append("---")
R.append("")
R.append("## Environment Variables")
R.append("")
R.append("### Backend (`backend/.env`)")
R.append("")
R.append("| Variable | Description | Example |")
R.append("|----------|-------------|---------|")
R.append("| `MONGODB_URL` | MongoDB Atlas connection string | `mongodb+srv://...` |")
R.append("| `DATABASE_NAME` | Database name | `cystar` |")
R.append("| `JWT_SECRET` | Secret key for JWT signing | `your-secret-key` |")
R.append("| `JWT_ALGORITHM` | JWT algorithm | `HS256` |")
R.append("| `JWT_EXPIRY_MINUTES` | Token expiry in minutes | `60` |")
R.append("| `FRONTEND_URL` | Frontend URL for CORS | `https://cystar-selective-disclosure.vercel.app` |")
R.append("")
R.append("### Frontend (`frontend/.env.local`)")
R.append("")
R.append("| Variable | Description | Example |")
R.append("|----------|-------------|---------|")
R.append("| `NEXT_PUBLIC_API_URL` | Backend API URL | `https://cystar-selective-disclosure.onrender.com` |")
R.append("")
R.append("---")
R.append("")
R.append("## Testing")
R.append("")
R.append("```bash")
R.append("cd backend")
R.append("pytest tests/test_sd_jwt.py -v")
R.append("```")
R.append("")
R.append("**12 tests covering:**")
R.append("")
R.append("- Ed25519 key generation, signing, verification")
R.append("- Disclosure creation, hashing, decoding")
R.append("- Full SD-JWT lifecycle")
R.append("- Selective disclosure (reveal 2 of 5 fields)")
R.append("- Tamper detection")
R.append("- Wrong key rejection")
R.append("- Issuer metadata preservation")
R.append("")
R.append("---")
R.append("")
R.append("## Security")
R.append("")
R.append("| Mechanism | Implementation |")
R.append("|-----------|---------------|")
R.append("| Digital Signatures | Ed25519 (EdDSA) via PyNaCl \u2014 128-bit security level |")
R.append("| Disclosure Hashing | SHA-256 with unique random salt per claim |")
R.append("| Password Storage | bcrypt via passlib \u2014 no plaintext storage |")
R.append("| Authentication | JWT with configurable expiry |")
R.append("| Link Expiry | MongoDB TTL indexes auto-delete expired presentations |")
R.append("| Rate Limiting | SlowAPI \u2014 10 req/min on verification endpoint |")
R.append("| CORS | Restricted to frontend origin |")
R.append("| Secrets | Environment variables, `.env` excluded from version control |")
R.append("")
R.append("---")
R.append("")
R.append("## Architecture Decision: SD-JWT vs Alternatives")
R.append("")
R.append("| Approach | Pros | Cons | Decision |")
R.append("|----------|------|------|----------|")
R.append("| **SD-JWT (chosen)** | IETF draft standard, simple, field-level disclosure, compact | Not ZKP, correlatable tokens | Selected |")
R.append("| Merkle Trees | Efficient batch proofs | Complex implementation, no formal spec | Rejected |")
R.append("| BBS+ Signatures | True ZKP, unlinkable proofs | Complex crypto, limited Python support | Future enhancement |")
R.append("| W3C VC + JSON-LD | Industry standard | Heavy spec, complex parsing | Over-engineered for scope |")
R.append("")
R.append("---")
R.append("")
R.append("## What I Would Improve")
R.append("")
R.append("- **BBS+ Signatures** \u2014 Zero-knowledge proofs for unlinkable presentations")
R.append("- **DID Integration** \u2014 Decentralized identifiers for issuer/holder identity")
R.append("- **Revocation Registry** \u2014 Allow issuers to revoke credentials")
R.append("- **HSM Key Storage** \u2014 Hardware security modules for production key management")
R.append("- **WebAuthn** \u2014 Passwordless authentication with FIDO2")
R.append("- **Credential Schema Registry** \u2014 Standardized claim schemas (OpenBadges v3)")
R.append("- **Audit Logging** \u2014 Immutable log of all issuance and verification events")
R.append("- **Multi-Issuer Support** \u2014 Multiple organizations issuing credentials")
R.append("- **Batch Verification** \u2014 Verify multiple credentials in one request")
R.append("- **Mobile App** \u2014 React Native companion app with biometric auth")
R.append("")
R.append("---")
R.append("")
R.append("## License")
R.append("")
R.append("MIT")
R.append("")
R.append("---")
R.append("")
R.append("*Built by Vishnu Aravind for CyStar \u2014 IIT Madras*")

content = "\n".join(R)

with open("README.md", "w", encoding="utf-8") as f:
    f.write(content)

print(f"README.md created ({len(content)} bytes, {len(R)} lines)")

for cmd in [
    ["git", "add", "README.md"],
    ["git", "commit", "-m", "docs: comprehensive README with architecture, API docs, security"],
    ["git", "push", "origin", "main"],
]:
    print(f"$ {' '.join(cmd)}")
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.stdout.strip():
        print(r.stdout.strip())
    if r.returncode != 0 and r.stderr.strip():
        print(r.stderr.strip())

print()
print("Done! Check GitHub.")
