services:
  - type: web
    name: cystar-backend
    runtime: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DATABASE_NAME
        value: cystar
      - key: FRONTEND_URL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
